var a = 10;
console.log(a);
var $ =10;
var _ = 10;
var _a =10;
var name = "abc";
var Name ="cde";
//var 12 =10; // syntax error because variable name cannot start with number
var ab123 =10;
//var sushree.sahoo = 10;
//var sushree sahoo = 10; // syntax error because variable name cannot contain space
var sushree_sahoo =10;
var sushree$sahoo = 10;
let totalPrice = 100;// camelCase used for js function and variables
let TotalPrice = 100;// PascalCase used for classes and constructor
let total_price = 100;// snake_case used for python function and variables
let strFirstname = "Sushree";// string Hungarian notation used for variable type
let bactive = true;// boolean Hungarian notation used for variable type
let arrItems = [1,2,3];// array Hungarian notation used for variable type
let numCount = 10;// number Hungarian notation used for variable type
// this is single line comment for not exicuted
/*
*
*this is multi line comment for not exicuted
*
*/ 
/**
*
*this is multi line comment for not exicuted
*
**/ 
