let age =34; // number literal
let isStudent = true; // boolean literal
let pi = 3.14; // number literal
let name = "sushree"; // string literal
let nullValue = null; // null literal
let undefinedValue = undefined; // undefined literal This variable is declared but not assigned any value, so it is undefined
console.log(typeof age);
console.log(typeof isStudent);
console.log(typeof pi);
console.log(typeof name);
console.log(typeof nullValue);
console.log(typeof undefinedValue);